<?php

$string['auth_collabcossodescription'] = 'Allows users to sign in using a SSO token generated by the Collabco Moodle Endpoint for Myday Moodle';
$string['pluginname'] = 'Collabco SSO Plugin';
$string['auth_collabcossotitle']  = 'Collabco SSO Plugin';
$string['collabcosso_nosettings'] = 'No settings for this plugin';

$string['salt'] = "Salt";
$string['salt_desc'] = "Used to secure SSO requests to the server";

$string['timedrift'] = 'Maximum Timedrift';
$string['timedrift_desc'] = 'The maximum allowed difference between the server clock and the client clock';

$string['hashingalgorithm'] = "Hashing Algorithm";
$string["hashingalgorithm_desc"] = "The hashing algorithm used by the server";

$string['verboselogging'] = "Verbose Logging";
$string["verboselogging_desc"] = "Creates detailed logs about each request";

$string['sso_failure'] = "SSO Failure";
$string['sso_verbose'] = "SSO Verbose";
$string['sso_success'] = "SSO Success";

$string['sso_parameterlog'] = "Username: %s \r\n"."Timestamp: %s \r\n"."Hash: %s \r\n"."URL: %s";

$string['sso_failure_settingincorrect'] = "The %s setting has not been configured correctly in the settings panel";
$string['sso_failure_unknownuser'] = "SSO request failed because the provided username '%s' could not be found";
$string['sso_failure_hashinvalid'] = "SSO request failed because the authentication hash provided is invalid";
$string['sso_failure_accountsuspended'] = "SSO request failed because the users account has been suspended";
$string['sso_failure_authunavailable'] = "SSO request failed because the users auth property is set to 'nologin' or a disabled auth provider.";
$string['sso_failure_linkexpired'] = "SSO request failed because the link used has expired";

$string['sso_verbose_hashinvalid'] = "SSO request aborted because the user is already logged in";

$string['sso_success_complete'] = "SSO request completed successfully";
?>